.PHONY: update-images build-images

update-images:
	build/update.sh
	test/update.sh
	test-systemd/update.sh
	testpublished/update.sh

build-images:
	build/build.sh
	test/build.sh
	test-systemd/build.sh
	testpublished/build.sh
