stages:
  - prepare
  - build
  - test
  - publish
  - test-published


# Google Cloud SDK image, used to auth with and push to the
# gcloud docker registry.  Used by the package server image build job.
prepare:gcloud-sdk-image:
  stage: prepare

  except:
    variables:
      - $BUILD == "integration"

  before_script:
    - |
        echo $CI_JOB_TOKEN | \
        docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  script:
    - |
        docker build \
            -t ${CI_REGISTRY_IMAGE}/gcloud:latest \
            -f .gitlab/Dockerfile.dind-gcloud \
            .gitlab/ \
        && docker push ${CI_REGISTRY_IMAGE}/gcloud:latest
  tags:
    - docker-in-docker


# Build the package server image used in the package service cluster.
build:server:
  stage: build

  dependencies:
    - prepare:gcloud-sdk-image

  except:
    variables:
      - $BUILD == "integration"

  variables:
    DOCKER_HOST: tcp://docker:2375/

  image: containers.magicstack.net/magicstack/edgedb-pkg-server/gcloud:latest

  services:
    - docker:dind

  script:
    - server/build-images.sh

  tags:
    - docker-in-docker


# This step builds the integration docker images
# used for the BUILD=integration jobs that actually
# build, test and publish the packages.
prepare:integration-images:
  before_script:
    - |
        echo $CI_JOB_TOKEN | \
        docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

  stage: prepare

  script:
    - integration/build-images.sh

  tags:
    - docker-in-docker


.debian: &debian
  PLATFORM: "debian"

.bionic: &bionic
  DISTRO: "bionic"


.integration:
  only:
    variables:
      - $BUILD == "integration"

  dependencies:
    - prepare:integration-images


.build: &build
  tags:
    - magiclamp

  extends: .integration
  stage: build

  cache:
    paths:
      - $HOME/.cache

  artifacts:
    paths:
      - artifacts

  script:
    - integration/${PLATFORM}/build.sh


.test: &test
  tags:
    - magiclamp

  extends: .integration
  stage: test

  script:
    - integration/${PLATFORM}/test.sh


.publish: &publish
  tags:
    - magiclamp

  extends: .integration
  stage: publish
  script:
    - integration/${PLATFORM}/publish.sh


.test-published: &test-published
  tags:
    - magiclamp

  extends: .integration
  stage: test-published
  script:
    - integration/${PLATFORM}/test-published.sh


build:ubuntu-bionic:
  variables:
    <<: [*debian, *bionic]
  image: containers.magicstack.net/magicstack/edgedb-pkg/python:3.7-bionic
  extends: .build


test:ubuntu-bionic:
  variables:
    <<: [*debian, *bionic]
  image: containers.magicstack.net/magicstack/edgedb-pkg/systemd:ubuntu-bionic
  dependencies:
    - build:ubuntu-bionic
  extends: .test


publish:ubuntu-bionic:
  variables:
    <<: [*debian, *bionic]
  image: containers.magicstack.net/magicstack/edgedb-pkg/upload:debian
  dependencies:
    - test:ubuntu-bionic
  extends: .publish


test-published:ubuntu-bionic:
  variables:
    <<: [*debian, *bionic]
  image: ubuntu:bionic
  dependencies:
    - publish:ubuntu-bionic
  extends: .test-published
