[tool.black]
line-length = 79
target-version = ["py39"]

[tool.ruff]
line-length = 79
indent-width = 4
exclude = [".github"]

[tool.mypy]
files = "edgedbpkg"
python_version = "3.9"
ignore_missing_imports = true
show_error_codes = true
strict = true
namespace_packages = true
