name: 'Build EdgeDB Package Server Images'
author: 'EdgeDB Inc.'
inputs:
  gcp_service_account:
    description: Google Cloud service account name.
    required: true
  gcp_service_key:
    description: Google Cloud service account key.
    required: true
  path:
    description: Path to container sources.
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
