name: 'describe-edgedb-package-artifact'
description: 'Describe an EdgeDB package artifact.'
author: 'EdgeDB Inc.'
inputs:
  target:
    description: 'Build Target'
  path:
    description: 'Artifact Root'
    default: '.'
outputs:
  metadata:
    description: 'Build metadata JSON'
  name:
    description: 'Package name'
  version:
    description: 'Full version (e.g. 1.0-beta.3+faa334)'
  version-slot:
    description: 'Version Slot (e.g. 1-beta-3)'
  version-core:
    description: 'Version without build metadata (e.g. 1.0-beta.3)'
  catalog-version:
    description: 'The catalog version of the server artifact (if server)'
  install-ref:
    description: 'The installation reference for the compiled artifact'
runs:
  using: 'node20'
  main: 'dist/index.js'
