name: 'describe-edgedb-package-artifact'
description: 'Describe an EdgeDB package artifact.'
author: 'EdgeDB Inc.'
inputs:
  target:
    description: 'Build Target'
  path:
    description: 'Artifact Root'
    default: '.'
outputs:
  metadata:
    description: 'Build metadata JSON'
  version-slot:
    description: 'Version Slot (e.g. 1-beta-3)'
  catalog-version:
    description: 'The catalog version of the server artifact (if server)'
  install-ref:
    description: 'The installation reference for the compiled artifact'
runs:
  using: 'node12'
  main: 'dist/index.js'
