apiVersion: v1
kind: Namespace
metadata:
  name: "<service-name>"
---

# Scratch space volumes for each repo.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genrepo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpmrepo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aptrepo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "<service-name>-upload"
  namespace: "default"
  labels:
    app: "<service-name>-upload"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "<service-name>-upload"
  template:
    metadata:
      labels:
        app: "<service-name>-upload"
    spec:
      containers:
      - name: "reprepro"
        image: "gcr.io/edgedb-infra/aptrepo:latest"
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: ""
        - name: PORT
          value: "2222"
        resources:
          requests:
            cpu: "10m"
        readinessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2222
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: root-authorized-keys
          readOnly: true
          mountPath: /root/.ssh/
        - name: gpg-keys
          readOnly: true
          mountPath: /root/gpg-keys/
        - name: uploader-authorized-keys
          readOnly: true
          mountPath: /etc/ssh/authorized_keys/
        - name: host-keys
          readOnly: true
          mountPath: /etc/ssh/
        - name: storage-credentials
          readOnly: true
          mountPath: /root/storage-credentials/
        - name: aptrepo-scratch
          mountPath: /var/tmp/repo/
        ports:
        - containerPort: 2222

      - name: "rpmrepo"
        image: "gcr.io/edgedb-infra/rpmrepo:latest"
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: ""
        - name: PORT
          value: "2223"
        resources:
          requests:
            cpu: "10m"
        readinessProbe:
          tcpSocket:
            port: 2223
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2223
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: root-authorized-keys
          readOnly: true
          mountPath: /root/.ssh/
        - name: gpg-keys
          readOnly: true
          mountPath: /root/gpg-keys/
        - name: uploader-authorized-keys
          readOnly: true
          mountPath: /etc/ssh/authorized_keys/
        - name: host-keys
          readOnly: true
          mountPath: /etc/ssh/
        - name: storage-credentials
          readOnly: true
          mountPath: /root/storage-credentials/
        - name: rpmrepo-scratch
          mountPath: /var/tmp/repo/
        ports:
        - containerPort: 2223

      - name: "genrepo"
        image: "gcr.io/edgedb-infra/genrepo:latest"
        imagePullPolicy: Always
        env:
        - name: DEBUG
          value: ""
        - name: PORT
          value: "2224"
        resources:
          requests:
            cpu: "10m"
        readinessProbe:
          tcpSocket:
            port: 2224
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 2224
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: root-authorized-keys
          readOnly: true
          mountPath: /root/.ssh/
        - name: gpg-keys
          readOnly: true
          mountPath: /root/gpg-keys/
        - name: uploader-authorized-keys
          readOnly: true
          mountPath: /etc/ssh/authorized_keys/
        - name: host-keys
          readOnly: true
          mountPath: /etc/ssh/
        - name: storage-credentials
          readOnly: true
          mountPath: /root/storage-credentials/
        - name: genrepo-scratch
          mountPath: /var/tmp/repo/
        ports:
        - containerPort: 2224

      volumes:
      - name: root-authorized-keys
        secret:
          defaultMode: 0400
          secretName: <service-name>-ssh-root-authorized-keys
      - name: uploader-authorized-keys
        secret:
          defaultMode: 0444
          secretName: <service-name>-ssh-uploader-authorized-keys
      - name: host-keys
        secret:
          defaultMode: 0400
          secretName: <service-name>-ssh-host-keys
      - name: gpg-keys
        secret:
          defaultMode: 0400
          secretName: <service-name>-gpg-keys
      - name: gpg-pub-keys
        secret:
          defaultMode: 0444
          secretName: <service-name>-gpg-pub-keys
      - name: storage-credentials
        secret:
          secretName: cloudstorage-mount-bot-credentials
          items:
          - key: key
            path: service-account-key.json
      - name: genrepo-scratch
        persistentVolumeClaim:
          claimName: genrepo-pvc
      - name: rpmrepo-scratch
        persistentVolumeClaim:
          claimName: rpmrepo-pvc
      - name: aptrepo-scratch
        persistentVolumeClaim:
          claimName: aptrepo-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: "<service-name>-upload"
  annotations:
    edbsre.edgedb.com/service.lb-static-ip-name: "<service-name>-upload"
spec:
  type: LoadBalancer
  selector:
    app: "<service-name>-upload"
  ports:
  - protocol: TCP
    name: deb-ssh-port
    port: 2222
    targetPort: 2222
  - protocol: TCP
    name: rpm-ssh-port
    port: 2223
    targetPort: 2223
  - protocol: TCP
    name: generic-ssh-port
    port: 2224
    targetPort: 2224
---
