FROM buildpack-deps:bullseye AS busybox
RUN apt-get update -y \
    && apt-get install -y musl-tools

ENV BUSYBOX_VERSION 1.34.1

RUN set -ex \
	\
    && ln -s /usr/include/x86_64-linux-gnu/asm/ /usr/include/x86_64-linux-musl/asm \
    && ln -s /usr/include/asm-generic/ /usr/include/x86_64-linux-musl/asm-generic \
    && ln -s /usr/include/linux/ /usr/include/x86_64-linux-musl/linux \
    && ln -s /usr/include/mtd/ /usr/include/x86_64-linux-musl/mtd \
	&& curl --proto '=https' --tlsv1.2 -sSf "https://busybox.net/downloads/busybox-${BUSYBOX_VERSION}.tar.bz2" > busybox.tar.bz2 \
	&& mkdir -p /usr/src/busybox \
	&& tar -xjC /usr/src/busybox --strip-components=1 -f busybox.tar.bz2 \
	&& rm busybox.tar.bz2 \
	&& cd /usr/src/busybox \
    && make defconfig \
    && sed -i \
        -e 's/.*CONFIG_STATIC\b.*/CONFIG_STATIC=y/' \
        -e 's/.*CONFIG_FEATURE_PREFER_APPLETS\b.*/CONFIG_FEATURE_PREFER_APPLETS=y/' \
        -e 's/.*CONFIG_FEATURE_SH_STANDALONE\b.*/CONFIG_FEATURE_SH_STANDALONE=y/' \
        .config \
    && cat .config \
    && echo 1 \
	&& make CC=musl-gcc -j "$(nproc)" \
    && cp busybox_unstripped /bin/busybox \
    && chmod +x /bin/busybox

FROM centos:7 AS glibc
RUN curl --proto '=https' --tlsv1.2 -sSfL \
        "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" \
        > /bin/jq \
    && chmod +x /bin/jq \
    && curl --proto '=https' --tlsv1.2 -sSfL \
        "https://github.com/tianon/gosu/releases/download/1.14/gosu-amd64" \
        > /bin/gosu \
    && chmod +x /bin/gosu

RUN repoquery -l "glibc" "glibc-common" \
	| grep -v --fixed-strings -- '/.build-id' \
	| grep -v --fixed-strings -- '/usr/share/doc' \
	| grep -v --fixed-strings -- '/usr/share/man' \
	| sed 's#^/##g' > "/tmp/contents" \
    && tar \
        --directory=/ \
        --create \
        --no-recursion \
        --sparse \
        --no-seek \
        --files-from=/tmp/contents \
        --file=/tmp/glibc.tar >/dev/null 2>&1 \
        || true

FROM scratch
COPY --from=busybox /bin/busybox /bin/busybox
COPY --from=glibc /bin/jq /bin/jq
COPY --from=glibc /bin/gosu /bin/gosu
COPY --from=glibc /tmp/glibc.tar /tmp/glibc.tar

RUN ["/bin/busybox", "ln", "/bin/busybox", "/bin/sh"]

RUN tar xf /tmp/glibc.tar -C / && rm /tmp/glibc.tar
RUN ln /bin/busybox /bin/echo
%%WRITE_ENTRYPOINT%%
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
